---
kind: pipeline
type: docker
name: code_quality_check

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: grafana/shipwright:go-latest
  commands:
  - go
  - build
  - -o
  - /var/scribe/pipeline
  - ./demo/multi-sub
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: scribe
    path: /var/scribe

- name: codeql
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=2 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug -version=latest ./demo/multi-sub
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - builtin-compile-pipeline

- name: notify_slack
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=3 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug -version=latest ./demo/multi-sub
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - codeql

volumes:
- name: scribe
  temp: {}
- name: scribe-state
  temp: {}
- name: docker_socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: grafana/shipwright:go-latest
  commands:
  - go
  - build
  - -o
  - /var/scribe/pipeline
  - ./demo/multi-sub
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: scribe
    path: /var/scribe

- name: install_frontend_dependencies
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=7 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug -version=latest ./demo/multi-sub
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - builtin-compile-pipeline

- name: install_backend_dependencies
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=8 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug -version=latest ./demo/multi-sub
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - install_frontend_dependencies

- name: test_backend
  image: grafana/shipwright:go-latest
  commands:
  - /var/scribe/pipeline -step=11 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug -version=latest ./demo/multi-sub
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - install_backend_dependencies

- name: test_frontend
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=12 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug -version=latest ./demo/multi-sub
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - install_backend_dependencies

volumes:
- name: scribe
  temp: {}
- name: scribe-state
  temp: {}
- name: docker_socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: publish

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: grafana/shipwright:go-latest
  commands:
  - go
  - build
  - -o
  - /var/scribe/pipeline
  - ./demo/multi-sub
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: scribe
    path: /var/scribe

- name: install_frontend_dependencies
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=15 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug -version=latest ./demo/multi-sub
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - builtin-compile-pipeline

- name: install_backend_dependencies
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=16 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug -version=latest ./demo/multi-sub
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - install_frontend_dependencies

- name: compile_backend
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=19 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug -version=latest ./demo/multi-sub
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - install_backend_dependencies

- name: compile_frontend
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=20 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug -version=latest ./demo/multi-sub
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - install_backend_dependencies

- name: publish
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=22 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug -version=latest -arg=gcp-publish-key=$secret_gcp_publish_key ./demo/multi-sub
  environment:
    secret_gcp_publish_key:
      from_secret: gcp-publish-key
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - compile_backend
  - compile_frontend

volumes:
- name: scribe
  temp: {}
- name: scribe-state
  temp: {}
- name: docker_socket
  host:
    path: /var/run/docker.sock

trigger:
  branch:
  - main
  event:
  - branch
  - tag
  ref:
  - refs/tags/v*

depends_on:
- test

...
