---
kind: pipeline
type: docker
name: code quality check

platform:
  os: linux
  arch: amd64

steps:
- name: codeql
  image: ghcr.io/grafana/shipwright:latest
  commands:
  - shipwright -step=1 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub

- name: notify-slack
  image: ghcr.io/grafana/shipwright:latest
  commands:
  - shipwright -step=2 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  depends_on:
  - codeql

---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: install-frontend-dependencies
  image: ghcr.io/grafana/shipwright:latest
  commands:
  - shipwright -step=7 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub

- name: install-backend-dependencies
  image: ghcr.io/grafana/shipwright:latest
  commands:
  - shipwright -step=8 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  depends_on:
  - install-frontend-dependencies

- name: test-backend
  image: ghcr.io/grafana/shipwright/go:latest
  commands:
  - shipwright -step=11 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  depends_on:
  - install-backend-dependencies

- name: test-frontend
  image: ghcr.io/grafana/shipwright:latest
  commands:
  - shipwright -step=12 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  depends_on:
  - install-backend-dependencies

---
kind: pipeline
type: docker
name: publish

platform:
  os: linux
  arch: amd64

steps:
- name: install-frontend-dependencies
  image: ghcr.io/grafana/shipwright:latest
  commands:
  - shipwright -step=15 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub

- name: install-backend-dependencies
  image: ghcr.io/grafana/shipwright:latest
  commands:
  - shipwright -step=16 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  depends_on:
  - install-frontend-dependencies

- name: compile-backend
  image: ghcr.io/grafana/shipwright:latest
  commands:
  - shipwright -step=19 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  depends_on:
  - install-backend-dependencies

- name: compile-frontend
  image: ghcr.io/grafana/shipwright:latest
  commands:
  - shipwright -step=20 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  depends_on:
  - install-backend-dependencies

- name: publish
  image: ghcr.io/grafana/shipwright:latest
  commands:
  - shipwright -step=22 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  environment:
    secret-gcp-publish-key:
      from_secret: gcp-publish-key
  depends_on:
  - compile-backend
  - compile-frontend

trigger:
  branch:
  - main
  event:
  - branch
  - tag
  ref:
  - refs/tags/v*

depends_on:
- test

...
