---
kind: pipeline
type: docker
name: code quality check

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: grafana/shipwright:go-latest
  command:
  - go
  - build
  - -o
  - /var/shipwright/pipeline
  - ./demo/multi-sub
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: shipwright
    path: /var/shipwright

- name: codeql
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=1 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - builtin-compile-pipeline

- name: notify-slack
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=2 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - codeql

volumes:
- name: shipwright
  temp: {}

---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: grafana/shipwright:go-latest
  command:
  - go
  - build
  - -o
  - /var/shipwright/pipeline
  - ./demo/multi-sub
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: shipwright
    path: /var/shipwright

- name: install-frontend-dependencies
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=7 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - builtin-compile-pipeline

- name: install-backend-dependencies
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=8 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - install-frontend-dependencies

- name: test-backend
  image: grafana/shipwright:go-latest
  commands:
  - /var/shipwright/pipeline -step=11 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - install-backend-dependencies

- name: test-frontend
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=12 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - install-backend-dependencies

volumes:
- name: shipwright
  temp: {}

---
kind: pipeline
type: docker
name: publish

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: grafana/shipwright:go-latest
  command:
  - go
  - build
  - -o
  - /var/shipwright/pipeline
  - ./demo/multi-sub
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: shipwright
    path: /var/shipwright

- name: install-frontend-dependencies
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=15 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - builtin-compile-pipeline

- name: install-backend-dependencies
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=16 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - install-frontend-dependencies

- name: compile-backend
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=19 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - install-backend-dependencies

- name: compile-frontend
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=20 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - install-backend-dependencies

- name: publish
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=22 -build-id=$DRONE_BUILD_NUMBER ./demo/multi-sub
  environment:
    secret-gcp-publish-key:
      from_secret: gcp-publish-key
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - compile-backend
  - compile-frontend

volumes:
- name: shipwright
  temp: {}

trigger:
  branch:
  - main
  event:
  - branch
  - tag
  ref:
  - refs/tags/v*

depends_on:
- test

...
