---
kind: pipeline
type: docker
name: basic_pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: golang:1.19
  command:
  - go
  - build
  - -o
  - /var/scribe/pipeline
  - ./demo/basic
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: scribe
    path: /var/scribe

- name: basic_pipeline
  image: golang:1.19
  command:
  - /var/scribe/pipeline
  - --pipeline="basic pipeline"
  - --build-id=$DRONE_BUILD_NUMBER
  - --state=file:///var/scribe-state/state.json
  - --log-level=debug
  - --version=latest
  - ./demo/basic
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - builtin-compile-pipeline

volumes:
- name: scribe
  temp: {}
- name: scribe-state
  temp: {}
- name: docker_socket
  host:
    path: /var/run/docker.sock

trigger:
  branch:
  - main
  event:
  - branch
  - tag
  ref:
  - refs/tags/v*

...
