---
kind: pipeline
type: docker
name: basic-pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: grafana/shipwright:go-latest
  command:
  - go
  - build
  - -o
  - /var/scribe/pipeline
  - ./demo/basic
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: scribe
    path: /var/scribe

- name: install-frontend-dependencies
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=0 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./demo/basic
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - builtin-compile-pipeline

- name: install-backend-dependencies
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=1 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./demo/basic
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - install-frontend-dependencies

- name: write-version-file
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=2 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./demo/basic
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - install-backend-dependencies

- name: compile-backend
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=6 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./demo/basic
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - write-version-file

- name: compile-frontend
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=7 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./demo/basic
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - compile-backend

- name: build-docker-image
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=8 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./demo/basic
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - compile-frontend

- name: publish
  image: grafana/shipwright:latest
  commands:
  - /var/scribe/pipeline -step=12 -arg=gcs-publish-key=$secret-gcs-publish-key -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug -arg=gcs-publish-key=$secret-$secret-gcs-publish-key ./demo/basic
  environment:
    $secret-gcs-publish-key:
      from_secret: gcs-publish-key
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build-docker-image

volumes:
- name: scribe
  temp: {}
- name: scribe-state
  temp: {}
- name: docker-socket
  host:
    path: /var/run/docker.sock

trigger:
  branch:
  - main
  event:
  - branch
  - tag
  ref:
  - refs/tags/v*

...
