---
kind: pipeline
type: docker
name: basic pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: grafana/shipwright:go-latest
  command:
  - go
  - build
  - -o
  - /var/shipwright/pipeline
  - ./demo/basic
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: shipwright
    path: /var/shipwright

- name: install-frontend-dependencies
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=0 -build-id=$DRONE_BUILD_NUMBER ./demo/basic
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - builtin-compile-pipeline

- name: install-backend-dependencies
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=1 -build-id=$DRONE_BUILD_NUMBER ./demo/basic
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - install-frontend-dependencies

- name: write-version-file
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=2 -build-id=$DRONE_BUILD_NUMBER ./demo/basic
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - install-backend-dependencies

- name: compile-backend
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=6 -build-id=$DRONE_BUILD_NUMBER ./demo/basic
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - write-version-file

- name: compile-frontend
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=7 -build-id=$DRONE_BUILD_NUMBER ./demo/basic
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - compile-backend

- name: publish
  image: grafana/shipwright:latest
  commands:
  - /var/shipwright/pipeline -step=10 -build-id=$DRONE_BUILD_NUMBER ./demo/basic
  environment:
    secret-gcs-publish-key:
      from_secret: gcs-publish-key
  volumes:
  - name: shipwright
    path: /var/shipwright
  depends_on:
  - compile-frontend

volumes:
- name: shipwright
  temp: {}

trigger:
  branch:
  - main
  event:
  - branch
  - tag
  ref:
  - refs/tags/v*

...
