---
kind: pipeline
type: docker
name: test_and_build

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: golang:1.19
  command:
  - go
  - build
  - -o
  - /var/scribe/pipeline
  - ./ci
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: scribe
    path: /var/scribe

- name: test_and_build
  image: golang:1.19
  command:
  - /var/scribe/pipeline
  - --pipeline
  - "'test and build'"
  - --build-id=$DRONE_BUILD_NUMBER
  - --state=file:///var/scribe-state/state.json
  - --log-level=debug
  - --version=v0.9.20-16-g7b28ce7
  - ./ci
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - builtin-compile-pipeline

volumes:
- name: scribe
  temp: {}
- name: scribe-state
  temp: {}
- name: docker_socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: create_github_release

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: golang:1.19
  command:
  - go
  - build
  - -o
  - /var/scribe/pipeline
  - ./ci
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: scribe
    path: /var/scribe

- name: create_github_release
  image: golang:1.19
  command:
  - /var/scribe/pipeline
  - --pipeline
  - "'create github release'"
  - --build-id=$DRONE_BUILD_NUMBER
  - --state=file:///var/scribe-state/state.json
  - --log-level=debug
  - --version=v0.9.20-16-g7b28ce7
  - ./ci
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - builtin-compile-pipeline

volumes:
- name: scribe
  temp: {}
- name: scribe-state
  temp: {}
- name: docker_socket
  host:
    path: /var/run/docker.sock

trigger:
  event:
  - tag

depends_on:
- test_and_build

...
