---
kind: pipeline
type: docker
name: test_and_build

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: grafana/shipwright:go-v0.9.3-21-g6b1f8ca
  command:
  - go
  - build
  - -o
  - /var/scribe/pipeline
  - ./ci
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: scribe
    path: /var/scribe

- name: test
  image: grafana/shipwright:go-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=1 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - builtin-compile-pipeline

- name: build_scribe_docker_image
  image: grafana/shipwright:docker-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=2 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - test

- name: build_git_image
  image: grafana/shipwright:docker-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=5 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build_scribe_docker_image

- name: build_go_image
  image: grafana/shipwright:docker-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=6 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build_git_image

- name: build_node_image
  image: grafana/shipwright:docker-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=7 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build_go_image

- name: build_docker_image
  image: grafana/shipwright:docker-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=8 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build_node_image

volumes:
- name: scribe
  temp: {}
- name: scribe-state
  temp: {}
- name: docker_socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: publish_docker_images

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: grafana/shipwright:go-v0.9.3-21-g6b1f8ca
  command:
  - go
  - build
  - -o
  - /var/scribe/pipeline
  - ./ci
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: scribe
    path: /var/scribe

- name: docker_login
  image: grafana/shipwright:docker-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=14 -arg=docker_username=$secret_docker_username -arg=docker_password=$secret_docker_password -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug -arg=docker_password=$secret_$secret_docker_password -arg=docker_username=$secret_$secret_docker_username ./ci
  environment:
    $secret_docker_password:
      from_secret: docker_password
    $secret_docker_username:
      from_secret: docker_username
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - builtin-compile-pipeline

- name: build_git_image
  image: grafana/shipwright:docker-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=16 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - docker_login

- name: build_go_image
  image: grafana/shipwright:docker-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=17 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build_git_image

- name: build_node_image
  image: grafana/shipwright:docker-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=18 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build_go_image

- name: build_docker_image
  image: grafana/shipwright:docker-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=19 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build_node_image

- name: list_images
  image: grafana/shipwright:v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=24 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build_docker_image

- name: push_scribe_docker_image
  image: grafana/shipwright:docker-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=26 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - list_images

- name: push_git
  image: grafana/shipwright:docker-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=28 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - push_scribe_docker_image

- name: push_go
  image: grafana/shipwright:docker-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=29 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - push_git

- name: push_node
  image: grafana/shipwright:docker-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=30 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - push_go

- name: push_docker
  image: grafana/shipwright:docker-v0.9.3-21-g6b1f8ca
  commands:
  - /var/scribe/pipeline -step=31 -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json -log-level=debug ./ci
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - push_node

volumes:
- name: scribe
  temp: {}
- name: scribe-state
  temp: {}
- name: docker_socket
  host:
    path: /var/run/docker.sock

depends_on:
- test_and_build

---
kind: signature
hmac: ffe7ff3b8f659c30168e363c5bd607195506832cb30b5248c320fbe1bc0f8fbe

...
