---
kind: pipeline
type: docker
name: test-and-build

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: grafana/shipwright:go-v0.9.3-4-gb0fa79e
  command:
  - go
  - build
  - -o
  - /var/scribe/pipeline
  - ./ci
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: scribe
    path: /var/scribe

- name: test
  image: grafana/shipwright:go-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=1 -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  volumes:
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - builtin-compile-pipeline

- name: build-scribe-docker-image
  image: grafana/shipwright:docker-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=2 -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - test

- name: build-git-image
  image: grafana/shipwright:docker-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=5 -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build-scribe-docker-image

- name: build-go-image
  image: grafana/shipwright:docker-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=6 -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build-git-image

- name: build-node-image
  image: grafana/shipwright:docker-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=7 -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build-go-image

- name: build-docker-image
  image: grafana/shipwright:docker-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=8 -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build-node-image

volumes:
- name: scribe
  temp: {}
- name: scribe-state
  temp: {}
- name: docker-socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: publish-docker-images

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: grafana/shipwright:go-v0.9.3-4-gb0fa79e
  command:
  - go
  - build
  - -o
  - /var/scribe/pipeline
  - ./ci
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: scribe
    path: /var/scribe

- name: docker-login
  image: grafana/shipwright:docker-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=14 -arg=docker_username=$secret-docker_username -arg=docker_password=$secret-docker_password -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  environment:
    $secret-docker_password:
      from_secret: docker_password
    $secret-docker_username:
      from_secret: docker_username
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - builtin-compile-pipeline

- name: build-git-image
  image: grafana/shipwright:docker-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=16 -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - docker-login

- name: build-go-image
  image: grafana/shipwright:docker-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=17 -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build-git-image

- name: build-node-image
  image: grafana/shipwright:docker-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=18 -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build-go-image

- name: build-docker-image
  image: grafana/shipwright:docker-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=19 -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build-node-image

- name: push-scribe-docker-image
  image: grafana/shipwright:docker-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=24 -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - build-docker-image

- name: push-git
  image: grafana/shipwright:docker-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=26 -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - push-scribe-docker-image

- name: push-go
  image: grafana/shipwright:docker-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=27 -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - push-git

- name: push-node
  image: grafana/shipwright:docker-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=28 -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - push-go

- name: push-docker
  image: grafana/shipwright:docker-v0.9.3-4-gb0fa79e
  commands:
  - /var/scribe/pipeline -step=29 -log-levle=debug -build-id=$DRONE_BUILD_NUMBER -state=file:///var/scribe-state/state.json ./ci
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: scribe
    path: /var/scribe
  - name: scribe-state
    path: /var/scribe-state
  depends_on:
  - push-node

volumes:
- name: scribe
  temp: {}
- name: scribe-state
  temp: {}
- name: docker-socket
  host:
    path: /var/run/docker.sock

depends_on:
- test-and-build

---
kind: signature
hmac: c591b1b53fa6b0ce72f7f6f2f1c5cd374ff55e568499619f7c46920f6d716491

...
