version: "3.9" 

services:
  grafana:
    image: grafana/grafana:8.3.4
    ports:
    - "3000:3000"
    volumes:
    - db-data:/var/lib/grafana
    - ./.compose/grafana/provisioning:/etc/grafana/provisioning
    - ./.compose/grafana/custom.ini:/etc/grafana/grafana.ini
    networks:
    - grafana
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_AUTH_DISABLE_LOGIN_FORM=true

  loki:
    image: grafana/loki:2.4.1
    ports:
    - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
    - ./.compose/loki/config.yaml:/etc/loki/local-config.yaml
    networks:
    - grafana

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
    - ./.compose/tempo/config.yaml:/etc/tempo.yaml
    - ./tempo-data:/tmp/tempo
    networks:
    - grafana
    ports:
    - "14268"  # jaeger ingest
    - "3200"   # tempo
    - "4317"  # otlp grpc
    - "4318"  # otlp http
    - "9411"   # zipkin

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
    - ./.compose/promtail/config.yml:/etc/loki/local-config.yml
    - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
    - grafana

networks:
  grafana:
volumes:
  db-data:
  tempo-data:
  logvolume01: {}
