name: grafana:build
labels:
  app: grafana
pipeline: "./build.go"
# Triggers define a list of actions or events that can cause this pipeline to start.
# Some pipelines could be started by a cron event, by an HTTP webhook event, or by a git event.
# Other pipelines may trigger from pubsub messages.
# To understand how these triggers are defined and how to create your own, visit {TODO INSERT DOC LINK}
triggers:
  - kind: scm:github
    event: "pr:comment"
  - kind: git
    event: commit
# Some built-in arguments are matched here by string.
# For example, if you were to name your argument, PR_ID, which is provided by the pr:* family of events, then it will be automatically populated.
# If triggering builds from other pipelines, then those pipelines can produce outputs.
arguments:
  PR_ID:
    kind: string

outputs:
  tarball:
    kind: fs
    glob: "./*.tar.gz"
