---
kind: pipeline
type: docker
name: basic pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: install-frontend-dependencies
  image: ghcr.io/grafana/shipwright:latest
  commands:
  - shipwright -step=0 -build-id=$DRONE_BUILD_NUMBER ./demo/basic

- name: install-backend-dependencies
  image: ghcr.io/grafana/shipwright:latest
  commands:
  - shipwright -step=1 -build-id=$DRONE_BUILD_NUMBER ./demo/basic
  depends_on:
  - install-frontend-dependencies

- name: write-version-file
  image: ghcr.io/grafana/shipwright:latest
  commands:
  - shipwright -step=2 -build-id=$DRONE_BUILD_NUMBER ./demo/basic
  depends_on:
  - install-backend-dependencies

- name: compile-backend
  image: ghcr.io/grafana/shipwright:latest
  commands:
  - shipwright -step=6 -build-id=$DRONE_BUILD_NUMBER ./demo/basic
  depends_on:
  - write-version-file

- name: compile-frontend
  image: ghcr.io/grafana/shipwright:latest
  commands:
  - shipwright -step=4 -build-id=$DRONE_BUILD_NUMBER ./demo/basic
  depends_on:
  - compile-backend

trigger:
  branch:
  - main
  event:
  - branch
  - tag
  ref:
  - refs/tags/v*

...
